In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

In [7]:
stocks = ['AAPL','AMZN','BA','CAT','CVX','GOOGL','GS','JNJ','JPM','KO','MCD','MSFT','NKE','NVDA','PFE','SOFI','TSLA','UNH','WMT','XOM']
data = pd.read_csv("Trading_Project_Data.csv", header=[0,1], index_col =0)
data.drop('Dividends', axis=1, inplace=True)
data.drop('Stock Splits', axis=1, inplace=True)
data = data.swaplevel(0,1,axis=1).sort_index(axis=1)
data.dropna(inplace=True)
tickers =data.columns.get_level_values(0).unique().tolist()
data = data.loc['1/3/2024':]
data

Ticker           AAPL                                                  \
Price           Close        High         Low        Open      Volume
Date
1/3/2024   179.012268  179.879127  176.740489  178.902664  73488000.0
4/3/2024   174.468719  176.262218  173.163430  175.514922  81510100.0
5/3/2024   169.506653  171.419729  169.008455  170.144345  95132400.0
6/3/2024   168.510254  170.622621  168.071838  170.443262  68587700.0
7/3/2024   168.390686  170.114444  167.882530  168.540139  71765100.0
...               ...         ...         ...         ...         ...
10/1/2025  236.850006  240.160004  233.000000  240.009995  61710900.0
13/1/2025  234.399994  234.669998  229.720001  233.529999  49630700.0
14/1/2025  233.279999  236.119995  232.470001  234.750000  39435300.0
15/1/2025  237.869995  238.960007  234.429993  234.639999  39832000.0
16/1/2025  228.259995  238.009995  228.029999  237.350006  71759100.0

Ticker           AMZN                                                  ...  \
Price           Close        High         Low        Open      Volume  ...
Date                                                                   ...
1/3/2024   178.220001  178.729996  176.070007  176.750000  31956200.0  ...
4/3/2024   177.580002  180.139999  177.490005  177.529999  37381500.0  ...
5/3/2024   174.119995  176.929993  173.300003  176.929993  37228300.0  ...
6/3/2024   173.509995  176.460007  173.259995  175.539993  32090900.0  ...
7/3/2024   176.820007  177.990005  173.720001  174.830002  34063300.0  ...
...               ...         ...         ...         ...         ...  ...
10/1/2025  218.940002  221.710007  216.500000  221.460007  36811500.0  ...
13/1/2025  218.460007  219.399994  216.470001  218.059998  27262700.0  ...
14/1/2025  217.759995  221.820007  216.199997  220.440002  24711700.0  ...
15/1/2025  223.350006  223.570007  220.750000  222.830002  31291300.0  ...
16/1/2025  220.660004  224.649994  220.309998  224.419998  24757300.0  ...

Ticker           WMT                                                      XOM  \
Price          Close       High        Low       Open      Volume       Close
Date
1/3/2024   58.064034  58.152968  57.510669  58.103561  19017700.0  103.299927
4/3/2024   58.597641  58.686575  57.708303  57.807117  16033300.0  101.855453
5/3/2024   59.328873  59.625319  58.874322  59.160884  19676900.0  103.104736
6/3/2024   59.852596  59.902003  59.328875  59.407925  12698700.0  104.207611
7/3/2024   59.645084  60.346674  59.635201  60.277503  16195300.0  104.793213
...              ...        ...        ...        ...         ...         ...
10/1/2025  93.000000  93.580002  92.199997  92.489998  18140900.0  106.540001
13/1/2025  91.529999  92.430000  91.099998  92.120003  18617100.0  109.290001
14/1/2025  90.790001  91.980003  90.570000  91.860001  13549200.0  109.720001
15/1/2025  91.339996  91.730003  90.809998  91.070000  17348200.0  111.510002
16/1/2025  91.300003  91.720001  90.120003  91.500000  13267700.0  111.320000

Ticker
Price            High         Low        Open      Volume
Date
1/3/2024   103.836730  102.850967  103.182811  18459500.0
4/3/2024   103.309693  101.533371  103.124258  18138000.0
5/3/2024   103.719614  101.816415  102.021375  19952700.0
6/3/2024   104.988415  103.602495  104.061217  20472800.0
7/3/2024   105.388574  104.041688  104.041688  15195400.0
...               ...         ...         ...         ...
10/1/2025  110.099998  105.779999  108.699997  19304500.0
13/1/2025  109.629997  107.129997  107.129997  17073400.0
14/1/2025  109.760002  107.830002  108.790001  11191200.0
15/1/2025  111.730003  109.470001  110.050003  14521100.0
16/1/2025  111.690002  110.550003  111.190002  10366600.0

[221 rows x 100 columns]

In [9]:
# obtaining more training data using yfinance 
new = yf.Tickers(stocks)
new_data = new.history(start = '2023-01-17', end = '2024-03-01')
new_data.drop('Dividends', axis=1, inplace=True)
new_data.drop('Stock Splits', axis=1, inplace=True)
new_data = new_data.swaplevel(0,1,axis=1).sort_index(axis=1)
new_data

[*********************100%***********************]  20 of 20 completed

Ticker            AAPL                                                 \
Price            Close        High         Low        Open     Volume
Date
2023-01-17  134.377625  135.712100  132.588430  133.280381   63646600
2023-01-18  133.655975  137.016892  133.478036  135.247471   69672800
2023-01-19  133.715302  134.684034  132.232542  132.538976   58280400
2023-01-20  136.285431  136.433716  132.677387  133.725202   80223600
2023-01-23  139.488174  141.672781  136.315061  136.532534   81760300
...                ...         ...         ...         ...        ...
2024-02-23  181.662231  184.170377  181.373586  184.140520   45119700
2024-02-26  180.308624  181.901096  179.801011  181.383551   40867400
2024-02-27  181.771713  183.055644  178.716134  180.248905   54318900
2024-02-28  180.567398  182.259406  179.283467  181.652272   48953900
2024-02-29  179.900543  181.711997  178.686276  180.418104  136682600

Ticker            AMZN                                                ...  \
Price            Close        High         Low        Open    Volume  ...
Date                                                                  ...
2023-01-17   96.050003   98.889999   95.730003   98.680000  72755000  ...
2023-01-18   95.459999   99.320000   95.379997   97.250000  79570400  ...
2023-01-19   93.680000   95.440002   92.860001   94.739998  69002700  ...
2023-01-20   97.250000   97.349998   93.199997   93.860001  67481500  ...
2023-01-23   97.519997   97.779999   95.860001   97.559998  76501100  ...
...                ...         ...         ...         ...       ...  ...
2024-02-23  174.990005  175.750000  173.699997  174.279999  59715200  ...
2024-02-26  174.729996  176.369995  174.259995  175.699997  44368600  ...
2024-02-27  173.539993  174.619995  172.860001  174.080002  31141700  ...
2024-02-28  173.160004  174.050003  172.270004  172.440002  28180500  ...
2024-02-29  176.759995  177.220001  172.850006  173.009995  53805400  ...

Ticker            WMT                                                    XOM  \
Price           Close       High        Low       Open    Volume       Close
Date
2023-01-17  46.723595  47.144208  46.655650  47.008319  15122400  104.663300
2023-01-18  45.568531  46.671829  45.452055  46.655652  22674300  102.513138
2023-01-19  44.918205  45.791783  44.905261  45.746488  17342100  103.171150
2023-01-20  45.471466  45.549116  44.704656  45.102620  29543100  105.052551
2023-01-23  46.150917  46.270630  45.361461  45.445583  13149900  104.505730
...               ...        ...        ...        ...       ...         ...
2024-02-23  57.668514  58.355044  57.586395  57.842610  74365800  100.449432
2024-02-26  58.732800  58.969309  57.333463  58.259784  32154800  100.846054
2024-02-27  58.722946  58.929890  58.358331  58.772218  18012700  100.633232
2024-02-28  58.752506  58.890469  58.447019  58.683525  14803300  100.913765
2024-02-29  57.757206  58.624403  57.737497  58.584984  29245100  101.107231

Ticker
Price             High         Low        Open    Volume
Date
2023-01-17  105.729119  104.422330  105.108166  16542200
2023-01-18  105.766201  102.318511  104.969154  16399700
2023-01-19  103.921854  101.558524  102.012653  12928000
2023-01-20  105.135967  102.513127  103.208225  16515600
2023-01-23  106.201764  104.394511  105.321309  16584400
...                ...         ...         ...       ...
2024-02-23  100.691269   99.520779  100.488127  15975900
2024-02-26  101.513527   99.685239  100.333361  13360800
2024-02-27  101.716665  100.459109  101.262010  16360000
2024-02-28  101.987522  100.604214  101.058869  14810500
2024-02-29  101.639276  100.817031  101.262010  17566100

[282 rows x 100 columns]

# Identifying Support and Resistance Levels

In [13]:

def identify_levels(data, window):
    data = data.copy()
    data["Support"] = data["Low"].rolling(window=window).min().shift()
    data["Resistance"] = data["High"].rolling(window=window).max().shift()
    data.dropna(inplace = True)
    return data

# Detect Breakouts

In [16]:

def detect_breakouts(data):
    data = data.copy()
    data["Bullish_Breakout"] = (data["Close"].copy().astype(float) > data["Resistance"])
    data["Bearish_Breakout"] = (data["Close"].copy().astype(float) < data["Support"])
    data.dropna(inplace = True)
    return data

# Defining Position

In [24]:
def pos(data):
    data = data.copy()

    # Initialize 'pos' column with 0
    data["pos"] = 0.0  

    # Vectorized conditional assignments
    data.loc[data["Bullish_Breakout"] & ~data["Bearish_Breakout"], "pos"] = 1.0
    data.loc[~data["Bullish_Breakout"] & data["Bearish_Breakout"], "pos"] = -0.5

    return data

# Computing Strategy Returns

In [27]:
def strat_returns(stock, window, df): 
    stock_data = df.xs(stock, axis=1, level=0)

    stock_data = identify_levels(stock_data, window) 
    stock_data = detect_breakouts(stock_data)
    stock_data = pos(stock_data)
    stock_data.dropna(inplace = True) 
    
    stock_data['Returns'] = np.log(stock_data['Close'].astype(float)/stock_data['Close'].astype(float).shift())
    stock_data.fillna(0, inplace = True)
    stock_data['Strat_Returns'] = stock_data['Returns']*stock_data['pos'].shift()
    #print('Total Returns =' ,np.exp(data['Strat_Returns'].sum()))
    ret = stock_data[['Returns','Strat_Returns']]
    return ret

# Varying Rolling Days

In [32]:
res = pd.DataFrame()
for stock in stocks:
    res[(f'{stock}','strat_ret')] =0.0
    res[(f'{stock}','Benchmark')] =0.0
    res[(f'{stock}','Outperform')] =0.0
    res.columns = pd.MultiIndex.from_tuples(res.columns)
    for i in [5,10,15,20, 25,28]: 
        ret = strat_returns(stock, i, new_data) 
        total_ret = float(np.exp(ret['Strat_Returns'].sum()))
        benchmark = float(np.exp(ret['Returns'].sum()))
        res.loc[f'{i}',(f'{stock}','strat_ret')] = total_ret
        res.loc[f'{i}',(f'{stock}','Benchmark')] = benchmark
        res.loc[f'{i}',(f'{stock}','Outperform')] = total_ret - benchmark 

res

        AAPL                           AMZN                             BA  \
   strat_ret Benchmark Outperform strat_ret Benchmark Outperform strat_ret
5   1.084338  1.276870  -0.192532  0.871357  1.835133  -0.963776  1.153740
10  1.046924  1.261295  -0.214371  0.806619  1.713953  -0.907334  1.163094
15  1.019138  1.176801  -0.157663  0.808544  1.731074  -0.922531  1.107170
20  0.976597  1.186128  -0.209531  0.840704  1.772919  -0.932215  1.124467
25  0.970450  1.220299  -0.249849  0.852834  1.845286  -0.992453  1.139931
28  0.976171  1.228467  -0.252296  0.852834  1.885239  -1.032405  1.155590

                              CAT  ...       TSLA       UNH            \
   Benchmark Outperform strat_ret  ... Outperform strat_ret Benchmark
5   0.961034   0.192706  1.121764  ...  -0.348626  1.032783  1.019185
10  0.956432   0.206662  0.976241  ...  -0.154153  1.003021  1.003688
15  0.948594   0.158576  0.971525  ...  -0.027202  0.982269  1.050644
20  0.932570   0.191896  1.042021  ...   0.076518  0.997397  1.016641
25  0.990086   0.149845  1.062064  ...   0.119606  0.984293  1.024834
28  1.016263   0.139327  1.054389  ...   0.164263  0.987805  1.036645

                    WMT                            XOM
   Outperform strat_ret Benchmark Outperform strat_ret Benchmark Outperform
5    0.013598  0.886181  1.248161  -0.361980  1.006670  0.958554   0.048116
10  -0.000667  0.913963  1.240786  -0.326823  1.021854  0.940376   0.081478
15  -0.068375  0.910040  1.266222  -0.356182  0.948528  0.949296  -0.000768
20  -0.019244  0.912113  1.226970  -0.314857  0.955128  0.929909   0.025219
25  -0.040542  0.934404  1.237603  -0.303200  0.923368  0.986603  -0.063236
28  -0.048839  0.913399  1.262103  -0.348704  0.926953  0.979286  -0.052332

[6 rows x 60 columns]

# Finding Best Outperformance per Stock

In [44]:
m = res.max(axis =0) # returns axis with best strat_returns 
m.xs('Outperform',level =1).sort_values(ascending=False) # seeing outperformance levels only

PFE      0.415803
BA       0.206662
NKE      0.171570
TSLA     0.164263
CVX      0.149093
JNJ      0.098821
XOM      0.081478
KO       0.022247
UNH      0.013598
GS       0.010960
MCD     -0.090224
AAPL    -0.157663
CAT     -0.200974
GOOGL   -0.249556
SOFI    -0.268365
JPM     -0.274799
WMT     -0.303200
MSFT    -0.640697
AMZN    -0.907334
NVDA    -2.343467
dtype: float64